services:
    flask:
        build: server
        image: qfortier/mtgscan-app
        ports:
            - '5000:5000'
        links:
            - redis

    celery:
        build: server
        image: qfortier/mtgscan-app
        command: "celery -A worker.celery worker --loglevel=info --uid=nobody"
        links:
            - redis
        environment:
            - AZURE_VISION_KEY
            - AZURE_VISION_ENDPOINT

    redis:
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes